### PR TITLE
Add logging

### LINKED ISSUE #20: twirp: server, add pluggable logging api
The API should be based on https://github.com/sirupsen/logrus

### PR DESCRIPTION
**Pull request by kevinbarbour**
fixes #20

### CODE REVIEW

**Comment by mmatczuk** [comment]
The `log.Logger` needs to be simplified:
* we only really need the key-value logging abstraction Error, Warn, Info, Debug, Trace, the control operations should not be exposed the f variants are not needed
* it must be usable without importing logrus

Actually we can use this interface on top of plain logrus logger.

**Comment by mmatczuk** [comment]
The echo logger should embed logrus, the interface is very similar lacking implementation of the `j` functions.

```
type Echo2Logger struct {
	logrus.Logger
}

func (e Echo2Logger) Output() io.Writer {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Prefix() string {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) SetPrefix(p string) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Level() elog.Lvl {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) SetLevel(v elog.Lvl) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) SetHeader(h string) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Printj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Debugj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Infoj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Warnj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Errorj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Fatalj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}

func (e Echo2Logger) Panicj(j elog.JSON) {
	//TODO implement me
	panic("implement me")
}
```

**Comment by kevinbarbour** [comment]
So we want just a single exposed function per logging level which logs both a message and any passed key/val pairs?

Can either do something similar to the scylla go-log package and allow 0 or more `interface{}` values then make sure it's an even number:
```go
func (l *Logger) Info(msg string, args ...interface{})
```

or can alias `logrus.Fields` (which is a `map[string]interface`) to a `Field` type in our package and do
```go
func (l *Logger) Info(msg string, Fields)
```

and use it like so
```go
logger.Info("log message", log.Fields{
    "value": 10,
    "otherValue": true,
})
```

But then if you want to log a message with no fields it's going to look like 
```go
logger.Info("log message", nil)
```

Preference between these two or were you thinking something different?



> Actually we can use this interface on top of plain logrus logger.

Also not entirely sure what you mean by this.

**Comment by kevinbarbour** [comment]
> The echo logger should embed logrus, the interface is very similar lacking implementation of the j functions.

Ah, gotcha. I thought we wanted this as a wrapper around our own logging package to avoid the logrus imports here as well. Will update.

**Comment by mmatczuk** [comment]
I doubt that we must put that to the middleware package.
This was my original idea but it looks like it would better go under cmd/log.go and we do not need to export anything.
Simply the cmd would take care of all the echo configuration.

**Comment by mmatczuk** [comment]
As for logrus it looks like it's not a right direction.
Let's try to make the scylla go-log easier to read see https://github.com/uber-go/zap/pull/123.
This would benefit Scylla Manager and other existing projects too.

**Comment by kevinbarbour** [comment]
New PR coming with go-log in favour of logrus.

**Comment by kevinbarbour** [comment]
New PR coming with go-log in favour of logrus.

**Pull request closed without merging**
